# Import List so we can return multiple citations in the response.
from typing import List

# Import Literal so we can restrict some values to fixed options.
from typing import Literal

# Import BaseModel so we can create FastAPI request and response models.
from pydantic import BaseModel

# Import Field so we can add validation rules like minimum and maximum values.
from pydantic import Field


# This model represents one citation returned with the final answer.
class Citation(BaseModel):
    # This is the unique chunk ID that supported the answer.
    chunk_id: str

    # This is the page number where the chunk came from.
    page_number: int

    # This is the Pinecone similarity score for the chunk.
    score: float

    # This is a short preview of the text used from the document.
    source_preview: str


# This model represents the user's /qa request body.
class QARequest(BaseModel):
    # This tells the system which document to search inside.
    document_id: str

    # This is the user's natural language question.
    question: str

    # This controls how many chunks we ask Pinecone to return.
    top_k: int = Field(default=5, ge=1, le=10)

    # This controls the minimum Pinecone score required to trust a chunk.
    min_score: float = Field(default=0.35, ge=0.0, le=1.0)


# This model represents the final /qa response body.
class QAResponse(BaseModel):
    # This is the final answer generated by Ollama.
    answer: str

    # This contains the list of document chunks that supported the answer.
    citations: List[Citation]

    # This tells us whether the answer was found, partially inferred, or not found.
    answer_status: Literal["found", "partial", "not_found"]

    # This tells us what type of question the system detected.
    question_type: Literal["direct_factual", "summary", "evidence_based_judgment"]